server:
  port: 8081

spring:
  application:
    name: AOP-SERVICE

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aop
    username: test
    password: test

  sql:
    init:
      mode: always

logging:
  level:
    com:
      example: debug
    org:
      springframework:
        orm:
          jpa: info
        transaction: info
        web: info
  track:
    time:
      switch: true
    async:
      time:
        switch: false